@startuml
class FinancialProject {
  String name
  Scout owner
  FinancialPlan financialPlan
}

enum Currency

class Money {
  double amount
  Currency currency
}

class PlanParameter {
  String name
  double number
}

class PlanItem {
  String name
  String description
  Expression unitAmount
  Expression quantity
}

class FinancialPlan {
  PlanItem[] incomes
  PlanItem[] expenses
}

class User {
  String givenName
  String familyName
}

class Scout {
  String ecset
  Status status
}

class Accountant {
  String email
  String password
}

User  <|-- Scout
User  <|-- Accountant

@enduml